### PR TITLE
Refer to teach-rs Matrix channel in README

### PR DESCRIPTION
**Pull request by hdoordt**
Figured I'd open a Matrix channel for people to ask questions in. Everyone welcome!

### CODE REVIEW

**Comment by hdoordt** [comment]
@LisetRoos @squell @tdittr I'd like to nudge people towards this channel if they need info or help, so please feel free to join and spread the word!

**Review by LisetRoos — APPROVED** [review]
Great idea, and looks good!

**Review by erikjee — APPROVED** [review]
Nice!

**Comment by hdoordt** [comment]
🥳

**Pull request merged**
